### Global Configuration ###
global:
  benchmark_name: WikiText 103
  output_dir: src/Benchmarks/WikiText/checkpoints

  logging:
    info_freq: 100
    local_log_path: src/Benchmarks/WikiText/experiments.log
    wandb:
      entity: m24842
      project: Machine Learning
      metrics: [acc, loss, ppl, seq_len, lr]
  
  dataset: # WikiText 2: 2,433,931 train samples | WikiText 103: 118,717,293 train samples
    name: WikiText
    splits:
      train:
        version: wikitext-103-raw-v1
        split: train
        tokenizer: EleutherAI/gpt-neox-20b
        min_len: 256
        max_len: 256
        warmup_epochs: 0
      val:
        version: wikitext-103-raw-v1
        split: validation
        tokenizer: EleutherAI/gpt-neox-20b
        max_len: 256
      test:
        version: wikitext-103-raw-v1
        split: test
        tokenizer: EleutherAI/gpt-neox-20b
        max_len: 256
  
  val_freqL: 500
  checkpoint_freq: 500

### Defaults ###
optimizer_defaults: &optimizer_defaults
  name: AdamW
  lr: 6e-4
  weight_decay: 0.1
  betas: [0.9, 0.95]

scheduler_defaults: &scheduler_defaults
  name: CosineAnnealingLRWithWarmup
  eta_min: 1e-5
  num_warmup_steps: 2000
  num_training_steps: 20000

Transformer_defaults: &Transformer_defaults
  general: &Transformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 16
    accumulation_steps: 3
    train_steps: 20000
    grad_clip_norm: 1.0
    mixed_precision: True
  
  model: &Transformer_model
    name: Transformer
    emb_dim: 128
    mlp_dim: 128
    n_heads: 4
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    mlp_bias: False
    attn_bias: False
    dropout: 0.0
    causal: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

CompressionTransformer_defaults: &CompressionTransformer_defaults
  general: &CompressionTransformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 16
    accumulation_steps: 3
    train_steps: 20000
    grad_clip_norm: 1.0
    mixed_precision: True
  
  model: &CompressionTransformer_model
    name: CompressionTransformer
    emb_dim: 128
    mlp_dim: 128
    mem_dim: 16
    n_heads: 4
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    mlp_bias: False
    attn_bias: False
    dropout: 0.0
    causal: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

LinearTransformer_defaults: &LinearTransformer_defaults
  general: &LinearTransformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 16
    accumulation_steps: 3
    train_steps: 20000
    grad_clip_norm: 1.0
    mixed_precision: True
  
  model: &LinearTransformer_model
    name: LinearTransformer
    emb_dim: 128
    mlp_dim: 128
    n_heads: 4
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    mlp_bias: False
    attn_bias: False
    dropout: 0.0
    causal: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

OrthoLinearTransformer_defaults: &OrthoLinearTransformer_defaults
  general: &OrthoLinearTransformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 16
    accumulation_steps: 3
    train_steps: 20000
    grad_clip_norm: 1.0
    mixed_precision: True
  
  model: &OrthoLinearTransformer_model
    name: OrthoLinearTransformer
    emb_dim: 128
    mlp_dim: 128
    n_heads: 4
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    mlp_bias: False
    attn_bias: False
    dropout: 0.0
    causal: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

SlidingWindowTransformer_defaults: &SlidingWindowTransformer_defaults
  general: &SlidingWindowTransformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 16
    accumulation_steps: 3
    train_steps: 20000
    grad_clip_norm: 1.0
    mixed_precision: True
  
  model: &SlidingWindowTransformer_model
    name: SlidingWindowTransformer
    emb_dim: 128
    mlp_dim: 128
    window_len: 64
    masked_window: False
    dilate: True
    # dilation_factor: 64
    n_heads: 4
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    mlp_bias: False
    attn_bias: False
    dropout: 0.0
    causal: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

FastTransformer_defaults: &FastTransformer_defaults
  general: &FastTransformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 64
    epochs: 10
    grad_clip_norm: 1.0
    mixed_precision: True
  
  model: &FastTransformer_model
    name: FastTransformer
    emb_dim: 128
    mlp_dim: 128
    window_len: 64
    n_dilations: 2
    # dilation_factor: 64
    n_heads: 4
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    attn_sink: True
    mlp_bias: False
    attn_bias: False
    dropout: 0.0
    causal: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

### Experiments Configuration ###
experiments:
  - <<: *FastTransformer_defaults
    general:
      <<: *FastTransformer_general
      seed: 0

  - <<: *FastTransformer_defaults
    general:
      <<: *FastTransformer_general
      seed: 42
  
  - <<: *FastTransformer_defaults
    general:
      <<: *FastTransformer_general
      seed: 1111
  
  - <<: *FastTransformer_defaults
    general:
      <<: *FastTransformer_general
      seed: 2222
  
  - <<: *FastTransformer_defaults
    general:
      <<: *FastTransformer_general
      seed: 3333
  
  - <<: *SlidingWindowTransformer_defaults
    general:
      <<: *SlidingWindowTransformer_general
      seed: 0

  - <<: *SlidingWindowTransformer_defaults
    general:
      <<: *SlidingWindowTransformer_general
      seed: 42
  
  - <<: *SlidingWindowTransformer_defaults
    general:
      <<: *SlidingWindowTransformer_general
      seed: 1111
  
  - <<: *SlidingWindowTransformer_defaults
    general:
      <<: *SlidingWindowTransformer_general
      seed: 2222
  
  - <<: *SlidingWindowTransformer_defaults
    general:
      <<: *SlidingWindowTransformer_general
      seed: 3333
  
  - <<: *CompressionTransformer_defaults
    general:
      <<: *CompressionTransformer_general
      seed: 0
  
  - <<: *CompressionTransformer_defaults
    general:
      <<: *CompressionTransformer_general
      seed: 42
  
  - <<: *CompressionTransformer_defaults
    general:
      <<: *CompressionTransformer_general
      seed: 1111
  
  - <<: *CompressionTransformer_defaults
    general:
      <<: *CompressionTransformer_general
      seed: 2222
  
  - <<: *CompressionTransformer_defaults
    general:
      <<: *CompressionTransformer_general
      seed: 3333
  
  - <<: *Transformer_defaults
    general:
      <<: *Transformer_general
      seed: 0
  
  - <<: *Transformer_defaults
    general:
      <<: *Transformer_general
      seed: 42
  
  - <<: *Transformer_defaults
    general:
      <<: *Transformer_general
      seed: 1111
  
  - <<: *Transformer_defaults
    general:
      <<: *Transformer_general
      seed: 2222
  
  - <<: *Transformer_defaults
    general:
      <<: *Transformer_general
      seed: 3333
  
  - <<: *OrthoLinearTransformer_defaults
    general:
      <<: *OrthoLinearTransformer_general
      seed: 0
  
  - <<: *OrthoLinearTransformer_defaults
    general:
      <<: *OrthoLinearTransformer_general
      seed: 42
  
  - <<: *OrthoLinearTransformer_defaults
    general:
      <<: *OrthoLinearTransformer_general
      seed: 1111
  
  - <<: *OrthoLinearTransformer_defaults
    general:
      <<: *OrthoLinearTransformer_general
      seed: 2222
  
  - <<: *OrthoLinearTransformer_defaults
    general:
      <<: *OrthoLinearTransformer_general
      seed: 3333
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 0
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 42
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 1111
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 2222
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 3333
  