### Global Configuration ###
global:
  benchmark_name: LAMBADA
  checkpoint_dir: src/Benchmarks/LAMBADA/checkpoints

  logging:
    info_freq: 100
    wandb:
      entity: m24842
      project: Machine Learning
  
  dataset: # 4,869 train samples
    name: LAMBADA
    splits:
      train:
        train: True
        tokenizer: EleutherAI/gpt-neox-20b
        min_len: 1024
        max_len: 2048
        warmup_epochs: 3
      test:
        train: False
        tokenizer: EleutherAI/gpt-neox-20b
        max_len: 2048
  
  checkpoint_freq: 500

### Defaults ###
general_defaults: &general_defaults
  load_checkpoint: False
  seed: 0
  batch_size: 16
  accumulation_steps: 3
  epochs: 20
  grad_clip_norm: 1.0
  mixed_precision: True

optimizer_defaults: &optimizer_defaults
  name: AdamW
  lr: 1e-3
  weight_decay: 0.01

scheduler_defaults: &scheduler_defaults
  name: CosineAnnealingLR
  T_max: 3050 # ceil(train_samples / batch_size) * epochs
  eta_min: 1e-6

Transformer_defaults: &Transformer_defaults
  general: &Transformer_general
    <<: *general_defaults
  
  model: &Transformer_model
    name: Transformer
    emb_dim: 128
    mlp_dim: 128
    n_heads: 4
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    dropout: 0.1
    causal: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

CompressionTransformer_defaults: &CompressionTransformer_defaults
  general: &CompressionTransformer_general
    <<: *general_defaults
  
  model: &CompressionTransformer_model
    name: CompressionTransformer
    emb_dim: 128
    mlp_dim: 128
    mem_dim: 16
    n_heads: 4
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    dropout: 0.1
    causal: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

LinearTransformer_defaults: &LinearTransformer_defaults
  general: &LinearTransformer_general
    <<: *general_defaults
  
  model: &LinearTransformer_model
    name: LinearTransformer
    emb_dim: 128
    mlp_dim: 128
    n_heads: 4
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    dropout: 0.1
    causal: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

OrthoLinearTransformer_defaults: &OrthoLinearTransformer_defaults
  general: &OrthoLinearTransformer_general
    <<: *general_defaults
  
  model: &OrthoLinearTransformer_model
    name: OrthoLinearTransformer
    emb_dim: 128
    mlp_dim: 128
    n_heads: 4
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    dropout: 0.1
    causal: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

SlidingWindowTransformer_defaults: &SlidingWindowTransformer_defaults
  general: &SlidingWindowTransformer_general
    <<: *general_defaults
  
  model: &SlidingWindowTransformer_model
    name: SlidingWindowTransformer
    emb_dim: 128
    mlp_dim: 128
    window_len: 64
    use_flex_attn: False
    dilate: True
    # dilation_factor: 64
    n_heads: 4
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    dropout: 0.1
    causal: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

Mamba2_defaults: &Mamba2_defaults
  general: &Mamba2_general
    <<: *general_defaults
  
  model: &Mamba2_model
    name: Mamba2
    emb_dim: 128
    mlp_dim: 128
    n_heads: 4
    n_layers: 12
    input_dim: 50277
    output_dim: 50277
    bidirectional: False
    use_embedding: True
    chunk_size: 256
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

### Experiments Configuration ###
experiments:
  - <<: *Mamba2_defaults
    general:
      <<: *Mamba2_general
      seed: 0

  - <<: *Mamba2_defaults
    general:
      <<: *Mamba2_general
      seed: 42
  
  - <<: *Mamba2_defaults
    general:
      <<: *Mamba2_general
      seed: 1111
  
  - <<: *Mamba2_defaults
    general:
      <<: *Mamba2_general
      seed: 2222
  
  - <<: *Mamba2_defaults
    general:
      <<: *Mamba2_general
      seed: 3333
  
  - <<: *SlidingWindowTransformer_defaults
    general:
      <<: *SlidingWindowTransformer_general
      seed: 0

  - <<: *SlidingWindowTransformer_defaults
    general:
      <<: *SlidingWindowTransformer_general
      seed: 42
  
  - <<: *SlidingWindowTransformer_defaults
    general:
      <<: *SlidingWindowTransformer_general
      seed: 1111
  
  - <<: *SlidingWindowTransformer_defaults
    general:
      <<: *SlidingWindowTransformer_general
      seed: 2222
  
  - <<: *SlidingWindowTransformer_defaults
    general:
      <<: *SlidingWindowTransformer_general
      seed: 3333
  
  - <<: *CompressionTransformer_defaults
    general:
      <<: *CompressionTransformer_general
      seed: 0
  
  - <<: *CompressionTransformer_defaults
    general:
      <<: *CompressionTransformer_general
      seed: 42
  
  - <<: *CompressionTransformer_defaults
    general:
      <<: *CompressionTransformer_general
      seed: 1111
  
  - <<: *CompressionTransformer_defaults
    general:
      <<: *CompressionTransformer_general
      seed: 2222
  
  - <<: *CompressionTransformer_defaults
    general:
      <<: *CompressionTransformer_general
      seed: 3333
  
  - <<: *Transformer_defaults
    general:
      <<: *Transformer_general
      seed: 0
  
  - <<: *Transformer_defaults
    general:
      <<: *Transformer_general
      seed: 42
  
  - <<: *Transformer_defaults
    general:
      <<: *Transformer_general
      seed: 1111
  
  - <<: *Transformer_defaults
    general:
      <<: *Transformer_general
      seed: 2222
  
  - <<: *Transformer_defaults
    general:
      <<: *Transformer_general
      seed: 3333
  
  - <<: *OrthoLinearTransformer_defaults
    general:
      <<: *OrthoLinearTransformer_general
      seed: 0
  
  - <<: *OrthoLinearTransformer_defaults
    general:
      <<: *OrthoLinearTransformer_general
      seed: 42
  
  - <<: *OrthoLinearTransformer_defaults
    general:
      <<: *OrthoLinearTransformer_general
      seed: 1111
  
  - <<: *OrthoLinearTransformer_defaults
    general:
      <<: *OrthoLinearTransformer_general
      seed: 2222
  
  - <<: *OrthoLinearTransformer_defaults
    general:
      <<: *OrthoLinearTransformer_general
      seed: 3333
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 0
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 42
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 1111
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 2222
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 3333
  