### Global Configuration ###
global:
  benchmark_name: ListOps
  output_dir: src/Python/Benchmarks/ListOps/models

  logging:
    info_freq: 100
    local_log_path: src/Python/Benchmarks/ListOps/experiments.log
    wandb:
      entity: m24842
      project: Machine Learning
      metrics: [acc, loss, seq_len, lr]
  
  dataset: # 96,000 train samples
    name: ListOps
    splits:
      train:
        root: data
        split: train
        min_len: 1024
        max_len: 1024
        warmup_epochs: 0
      val:
        root: data
        split: val
        max_len: 2048
      test:
        root: data
        split: test
        max_len: 2048
  
  checkpoint_freq: 500

### Defaults ###
optimizer_defaults: &optimizer_defaults
  name: AdamW
  lr: 3e-4
  weight_decay: 0.01

scheduler_defaults: &scheduler_defaults
  name: CosineAnnealingLR
  T_max: 30000 # ceil(train_samples / batch_size) * epochs
  eta_min: 1e-6

Transformer_defaults: &Transformer_defaults
  general: &Transformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 32
    epochs: 10
    grad_clip_norm: 1.0
  
  model: &Transformer_model
    name: Transformer
    emb_dim: 128
    mlp_dim: 128
    n_heads: 4
    n_layers: 4
    input_dim: 17
    output_dim: 10
    dropout: 0.1
    causal: False
    use_embedding: True
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

CompressionTransformer_defaults: &CompressionTransformer_defaults
  general: &CompressionTransformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 32
    epochs: 10
    grad_clip_norm: 1.0
  
  model: &CompressionTransformer_model
    name: CompressionTransformer
    emb_dim: 128
    mlp_dim: 128
    mem_dim: 16
    n_heads: 4
    n_layers: 4
    input_dim: 17
    output_dim: 10
    dropout: 0.1
    causal: False
    use_embedding: True
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

LinearTransformer_defaults: &LinearTransformer_defaults
  general: &LinearTransformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 32
    epochs: 10
    grad_clip_norm: 1.0
  
  model: &LinearTransformer_model
    name: LinearTransformer
    emb_dim: 128
    mlp_dim: 128
    n_heads: 4
    n_layers: 4
    input_dim: 17
    output_dim: 10
    dropout: 0.1
    causal: False
    use_embedding: True
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

OrthoLinearTransformer_defaults: &OrthoLinearTransformer_defaults
  general: &OrthoLinearTransformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 32
    epochs: 10
    grad_clip_norm: 1.0
  
  model: &OrthoLinearTransformer_model
    name: OrthoLinearTransformer
    emb_dim: 128
    mlp_dim: 128
    n_heads: 4
    n_layers: 4
    input_dim: 17
    output_dim: 10
    dropout: 0.1
    causal: False
    use_embedding: True
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

### Experiments Configuration ###
experiments:
  # - <<: *CompressionTransformer_defaults
  #   general:
  #     <<: *CompressionTransformer_general
  #     seed: 0
  
  # - <<: *CompressionTransformer_defaults
  #   general:
  #     <<: *CompressionTransformer_general
  #     seed: 42
  
  # - <<: *CompressionTransformer_defaults
  #   general:
  #     <<: *CompressionTransformer_general
  #     seed: 1111
  
  # - <<: *CompressionTransformer_defaults
  #   general:
  #     <<: *CompressionTransformer_general
  #     seed: 2222
  
  # - <<: *CompressionTransformer_defaults
  #   general:
  #     <<: *CompressionTransformer_general
  #     seed: 3333
  
  # - <<: *Transformer_defaults
  #   general:
  #     <<: *Transformer_general
  #     seed: 0
  
  # - <<: *Transformer_defaults
  #   general:
  #     <<: *Transformer_general
  #     seed: 42
  
  # - <<: *Transformer_defaults
  #   general:
  #     <<: *Transformer_general
  #     seed: 1111
  
  # - <<: *Transformer_defaults
  #   general:
  #     <<: *Transformer_general
  #     seed: 2222
  
  # - <<: *Transformer_defaults
  #   general:
  #     <<: *Transformer_general
  #     seed: 3333
  
  # - <<: *OrthoLinearTransformer_defaults
  #   general:
  #     <<: *OrthoLinearTransformer_general
  #     seed: 0
  
  # - <<: *OrthoLinearTransformer_defaults
  #   general:
  #     <<: *OrthoLinearTransformer_general
  #     seed: 42
  
  # - <<: *OrthoLinearTransformer_defaults
  #   general:
  #     <<: *OrthoLinearTransformer_general
  #     seed: 1111
  
  # - <<: *OrthoLinearTransformer_defaults
  #   general:
  #     <<: *OrthoLinearTransformer_general
  #     seed: 2222
  
  # - <<: *OrthoLinearTransformer_defaults
  #   general:
  #     <<: *OrthoLinearTransformer_general
  #     seed: 3333
  
  # - <<: *LinearTransformer_defaults
  #   general:
  #     <<: *LinearTransformer_general
  #     seed: 0
  
  # - <<: *LinearTransformer_defaults
  #   general:
  #     <<: *LinearTransformer_general
  #     seed: 42
  
  # - <<: *LinearTransformer_defaults
  #   general:
  #     <<: *LinearTransformer_general
  #     seed: 1111
  
  # - <<: *LinearTransformer_defaults
  #   general:
  #     <<: *LinearTransformer_general
  #     seed: 2222
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 3333
  