### Global Configuration ###
global:
  benchmark_name: The Pile
  checkpoint_dir: src/Benchmarks/ThePile/checkpoints

  logging:
    info_freq: 100
    wandb:
      entity: m24842
      project: Machine Learning
  
  dataset: # 177,009,664 train samples
    name: ThePile
    splits:
      train:
        root: data
        split: train
        tokenizer: EleutherAI/gpt-neox-20b
        min_len: 512
        max_len: 512
        warmup_epochs: 0
        num_proc: 8
        shard_size: 10000000
      val:
        root: data
        split: val
        tokenizer: EleutherAI/gpt-neox-20b
        max_len: 1024
        num_proc: 8
        shard_size: 10000000
      test:
        root: data
        split: test
        tokenizer: EleutherAI/gpt-neox-20b
        max_len: 1024
        num_proc: 8
        shard_size: 10000000
  
  val_freq: 1000
  checkpoint_freq: 500

### Defaults ###
general_defaults: &general_defaults
  load_checkpoint: False
  seed: 0
  batch_size: 64
  accumulation_steps: 1
  train_steps: 5000
  grad_clip_norm: 1.0
  mixed_precision: False
  num_workers: 8

optimizer_defaults: &optimizer_defaults
  name: AdamW
  lr: 6e-4
  weight_decay: 0.01
  betas: [0.9, 0.95]

scheduler_defaults: &scheduler_defaults
  name: CosineAnnealingLRWithWarmup
  eta_min: 1e-6
  num_warmup_steps: 500
  num_training_steps: 5000

Transformer_defaults: &Transformer_defaults
  general: &Transformer_general
    <<: *general_defaults
  
  model: &Transformer_model
    name: Transformer
    emb_dim: 768
    ff_dim: 2304
    n_heads: 12
    n_layers: 12
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    ff_bias: False
    attn_bias: False
    causal: True
    weight_tying: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

CompressionTransformer_defaults: &CompressionTransformer_defaults
  general: &CompressionTransformer_general
    <<: *general_defaults
  
  model: &CompressionTransformer_model
    name: CompressionTransformer
    emb_dim: 768
    ff_dim: 2304
    mem_dim: 64
    n_heads: 12
    n_layers: 12
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    ff_bias: False
    attn_bias: False
    causal: True
    weight_tying: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

LinearTransformer_defaults: &LinearTransformer_defaults
  general: &LinearTransformer_general
    <<: *general_defaults
  
  model: &LinearTransformer_model
    name: LinearTransformer
    emb_dim: 768
    ff_dim: 2304
    n_heads: 12
    n_layers: 12
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    ff_bias: False
    attn_bias: False
    causal: True
    weight_tying: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

OrthoLinearTransformer_defaults: &OrthoLinearTransformer_defaults
  general: &OrthoLinearTransformer_general
    <<: *general_defaults
  
  model: &OrthoLinearTransformer_model
    name: OrthoLinearTransformer
    emb_dim: 768
    ff_dim: 2304
    n_heads: 12
    n_layers: 12
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    ff_bias: False
    attn_bias: False
    causal: True
    weight_tying: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

SlidingWindowTransformer_defaults: &SlidingWindowTransformer_defaults
  general: &SlidingWindowTransformer_general
    <<: *general_defaults
  
  model: &SlidingWindowTransformer_model
    name: SlidingWindowTransformer
    emb_dim: 768
    ff_dim: 2304
    window_len: 64
    use_flex_attn: False
    dilate: True
    # dilation_factor: 64
    n_heads: 12
    n_layers: 12
    input_dim: 50277
    output_dim: 50277
    attn_sink: False
    ff_bias: False
    attn_bias: False
    causal: True
    weight_tying: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

Mamba2_defaults: &Mamba2_defaults
  general: &Mamba2_general
    <<: *general_defaults
  
  model: &Mamba2_model
    name: Mamba2
    emb_dim: 768
    d_state: 128
    n_heads: 12
    n_layers: 24
    input_dim: 50277
    output_dim: 50277
    bidirectional: False
    use_embedding: True
    chunk_size: 256
    weight_tying: True
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

SeqMLP_defaults: &SeqMLP_defaults
  general: &SeqMLP_general
    <<: *general_defaults
  
  model: &SeqMLP_model
    name: SeqMLP
    emb_dim: 768
    d_state: 768
    d_inner: 1536
    n_heads: 12
    n_layers: 24
    input_dim: 50277
    output_dim: 50277
    mode: causal
    use_embedding: True
    weight_tying: True
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

### Experiments Configuration ###
experiments:
  - <<: *SeqMLP_defaults
    general:
      <<: *SeqMLP_general
      seed: 0
      batch_size: 32
      accumulation_steps: 16

  - <<: *Mamba2_defaults
    general:
      <<: *Mamba2_general
      seed: 0

  - <<: *SlidingWindowTransformer_defaults
    general:
      <<: *SlidingWindowTransformer_general
      seed: 0

  - <<: *CompressionTransformer_defaults
    general:
      <<: *CompressionTransformer_general
      seed: 0
  
  - <<: *Transformer_defaults
    general:
      <<: *Transformer_general
      seed: 0
  
  - <<: *OrthoLinearTransformer_defaults
    general:
      <<: *OrthoLinearTransformer_general
      seed: 0
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 0
  