### Global Configuration ###
global:
  benchmark_name: The Pile
  output_dir: src/Benchmarks/ThePile/checkpoints

  logging:
    info_freq: 100
    local_log_path: src/Benchmarks/ThePile/experiments.log
    wandb:
      entity: m24842
      project: Machine Learning
      metrics: [acc, loss, ppl, seq_len, lr]
  
  dataset: # 892,000 train samples
    name: ThePile
    splits:
      train:
        split: train
        tokenizer: EleutherAI/gpt-neox-20b
        min_len: 256
        max_len: 256
        warmup_epochs: 0
      val:
        split: validation
        tokenizer: EleutherAI/gpt-neox-20b
        max_len: 256
        num_proc: 8
      test:
        split: test
        tokenizer: EleutherAI/gpt-neox-20b
        max_len: 256
        num_proc: 8
  
  checkpoint_freq: 500

### Defaults ###
optimizer_defaults: &optimizer_defaults
  name: AdamW
  lr: 3e-4
  weight_decay: 0.01

scheduler_defaults: &scheduler_defaults
  name: CosineAnnealingLRWithWarmup
  num_warmup_steps: 27875
  num_training_steps: 557500 # ceil(train_samples / batch_size) * epochs

Transformer_defaults: &Transformer_defaults
  general: &Transformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 16
    epochs: 20
    grad_clip_norm: 1.0
    dynamic_precision: True
  
  model: &Transformer_model
    name: Transformer
    emb_dim: 512
    mlp_dim: 1024
    n_heads: 8
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    dropout: 0.1
    causal: True
    weight_tying: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

CompressionTransformer_defaults: &CompressionTransformer_defaults
  general: &CompressionTransformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 16
    epochs: 20
    grad_clip_norm: 1.0
    dynamic_precision: True
  
  model: &CompressionTransformer_model
    name: CompressionTransformer
    emb_dim: 512
    mlp_dim: 1024
    mem_dim: 16
    n_heads: 8
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    dropout: 0.1
    causal: True
    weight_tying: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

LinearTransformer_defaults: &LinearTransformer_defaults
  general: &LinearTransformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 16
    epochs: 20
    grad_clip_norm: 1.0
    dynamic_precision: True
  
  model: &LinearTransformer_model
    name: LinearTransformer
    emb_dim: 512
    mlp_dim: 1024
    n_heads: 8
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    dropout: 0.1
    causal: True
    weight_tying: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

OrthoLinearTransformer_defaults: &OrthoLinearTransformer_defaults
  general: &OrthoLinearTransformer_general
    load_checkpoint: False
    seed: 0
    batch_size: 16
    epochs: 20
    grad_clip_norm: 1.0
    dynamic_precision: True
  
  model: &OrthoLinearTransformer_model
    name: OrthoLinearTransformer
    emb_dim: 512
    mlp_dim: 1024
    n_heads: 8
    n_layers: 6
    input_dim: 50277
    output_dim: 50277
    dropout: 0.1
    causal: True
    weight_tying: True
    use_embedding: True
    pos_encoding: xpos
  
  optimizer:
    <<: *optimizer_defaults
  
  scheduler:
    <<: *scheduler_defaults

### Experiments Configuration ###
experiments:
  - <<: *CompressionTransformer_defaults
    general:
      <<: *CompressionTransformer_general
      seed: 0
  
  # - <<: *CompressionTransformer_defaults
  #   general:
  #     <<: *CompressionTransformer_general
  #     seed: 42
  
  # - <<: *CompressionTransformer_defaults
  #   general:
  #     <<: *CompressionTransformer_general
  #     seed: 1111
  
  # - <<: *CompressionTransformer_defaults
  #   general:
  #     <<: *CompressionTransformer_general
  #     seed: 2222
  
  # - <<: *CompressionTransformer_defaults
  #   general:
  #     <<: *CompressionTransformer_general
  #     seed: 3333
  
  - <<: *Transformer_defaults
    general:
      <<: *Transformer_general
      seed: 0
  
  # - <<: *Transformer_defaults
  #   general:
  #     <<: *Transformer_general
  #     seed: 42
  
  # - <<: *Transformer_defaults
  #   general:
  #     <<: *Transformer_general
  #     seed: 1111
  
  # - <<: *Transformer_defaults
  #   general:
  #     <<: *Transformer_general
  #     seed: 2222
  
  # - <<: *Transformer_defaults
  #   general:
  #     <<: *Transformer_general
  #     seed: 3333
  
  - <<: *OrthoLinearTransformer_defaults
    general:
      <<: *OrthoLinearTransformer_general
      seed: 0
  
  # - <<: *OrthoLinearTransformer_defaults
  #   general:
  #     <<: *OrthoLinearTransformer_general
  #     seed: 42
  
  # - <<: *OrthoLinearTransformer_defaults
  #   general:
  #     <<: *OrthoLinearTransformer_general
  #     seed: 1111
  
  # - <<: *OrthoLinearTransformer_defaults
  #   general:
  #     <<: *OrthoLinearTransformer_general
  #     seed: 2222
  
  # - <<: *OrthoLinearTransformer_defaults
  #   general:
  #     <<: *OrthoLinearTransformer_general
  #     seed: 3333
  
  - <<: *LinearTransformer_defaults
    general:
      <<: *LinearTransformer_general
      seed: 0
  
  # - <<: *LinearTransformer_defaults
  #   general:
  #     <<: *LinearTransformer_general
  #     seed: 42
  
  # - <<: *LinearTransformer_defaults
  #   general:
  #     <<: *LinearTransformer_general
  #     seed: 1111
  
  # - <<: *LinearTransformer_defaults
  #   general:
  #     <<: *LinearTransformer_general
  #     seed: 2222
  
  # - <<: *LinearTransformer_defaults
  #   general:
  #     <<: *LinearTransformer_general
  #     seed: 3333
  